### PR TITLE
Updated RMC App icon

### PR DESCRIPTION
**Pull request by vderlinden**
- [Added Adaptive Icon for Android 8.0+ (API level 26)](https://github.com/Digital-Architects-Avans/rmc-app/commit/6f772f0b3e09774e51582d64a680596c6764615e)
- [Added legacy launcher icons for older devices](https://github.com/Digital-Architects-Avans/rmc-app/commit/f7ce0ebca3fff1323ae3c9e9df340a6eda47ec74)
- [Updated avd_rmc_logo_anim.xml with new icon](https://github.com/Digital-Architects-Avans/rmc-app/commit/c71745dc955027d59ee76ad25ba19b55d2caff6a)
- [Updated Playstore image](https://github.com/Digital-Architects-Avans/rmc-app/commit/ff81349dc44ae1943c4d99176eb5eae0dbbba7df)

Additionally, @AlexVDV116 can you please have a look at the following?:
- app/src/main/res/drawable/rmc_logo_app.xml -> This file can be replaced by app/src/main/res/drawable/ic_launcher_foreground.xml?

### CODE REVIEW

**Review by AlexVDV116 — APPROVED** [review]
Goed bezig, nieuw icon ziet er goed uit!  👍

**Comment by vderlinden** [comment]
app/src/main/res/drawable/rmc_logo_app.xml kan dus weg @AlexVDV116 ?

**Comment by AlexVDV116** [comment]
> app/src/main/res/drawable/rmc_logo_app.xml kan dus weg @AlexVDV116 ?

Ja.

**Comment by vderlinden** [comment]
> > app/src/main/res/drawable/rmc_logo_app.xml kan dus weg @AlexVDV116 ?
> 
> Ja.

Check!
https://github.com/Digital-Architects-Avans/rmc-app/commit/20c24a91f96abca99b604c32bb679e5d54f778aa

**Pull request merged**
